#!/bin/bash
read -p "Update hostname? [y/N]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	echo 'New hostname: '
	read hostname_update
	hostnamectl set-hostname $hostname_update
fi

echo Installing git
sudo apt-get install -y git

workspace=~/Workspace/frbl/
mkdir -p $workspace
cd $workspace

if [ ! -d "evionix-net" ]; then
	git clone git@github.com:frbl/evionix-net.git
fi

echo Running salt setup
cd evionix-net/salt/
./salt_linux_minion_setup.sh
