#!/bin/bash
echo "Installing frbl vimrc"
dir=`pwd`
cd ~
apt-get install -y git vim tmux

mkdir Drive
cd Drive
git clone git@github.com:frbl/dotfiles.git
./setup.sh
cd ~

mv .vimrc .vimrc-old
mkdir -p .vim/bundle/
git clone https://github.com/VundleVim/Vundle.vim.git .vim/bundle/Vundle.vim
curl -X GET "https://docs.google.com/uc?authuser=0&amp;id=0Bw5OJuNu4skMZHJEXzZhVXpfOWc&amp;export=download" > .vimrc
vim +PluginInstll +qall
cd $dir
echo "Installed frbl vimrc"
