#!/bin/bash
echo "Installing frbl vimrc"
cd ~
mv .vimrc .vimrc-old
mkdir -p .vim/bundle/
git clone https://github.com/VundleVim/Vundle.vim.git .vim/bundle/Vundle.vim
wget -O .vimrc http://goo.gl/45PoJG
vim +PluginInstll +qall
echo "Installed frbl vimrc"
